### ISSUE TITLE
Update benchmarks (compatible with Formulary)

### ISSUE THREAD

**Issue by diego7319** [PlasmaPy/plasmapy-benchmarks#5]
I think the code needs an update since the last major change (formulary), I would like to address this.

**Comment by StanczakDominik** [comment]
Yeah, I've been trying to get it to work with the refactor and mostly failing. I think we could have try/except ImportError clauses for the imports and that should potentially work, though!

**Comment by diego7319** [comment]
I was thinking in creating the same carpets structure because it seems a little messy (I dont know if thats just me) . I am getting an error with mass_density test, I'll fix it.
